Repository angular/devkit, pull requests merged in 2018-03, with the labels that each got.

#472 feat(@angular-devkit/core): add support for smart defaults in the Core Schema Registry
  packages/angular_devkit/core/src/json/schema/index.ts
  packages/angular_devkit/core/src/json/schema/interface.ts
  packages/angular_devkit/core/src/json/schema/pointer.ts
  packages/angular_devkit/core/src/json/schema/registry.ts
  packages/angular_devkit/core/src/json/schema/registry_spec.ts
  packages/angular_devkit/core/src/json/schema/transforms.ts
  packages/angular_devkit/core/src/json/schema/visitor.ts
Labels: cla: yes

#483 refactor(@angular-devkit/build-webpack): update deps for webpack 4
  package-lock.json
  package.json
  packages/angular_devkit/build_webpack/package.json
Labels: cla: yes

#485 test: Add ability to run external schematics
  packages/angular_devkit/schematics/testing/schematic-test-runner.ts
Labels: cla: yes

#487 fix(@angular-devkit/core): remove functions that have no files from c…
  packages/angular_devkit/core/node/resolve.ts
Labels: cla: yes

#488 build: add CI-specific Bazel settings
  .circleci/bazel.rc
  .circleci/config.yml
Labels: cla: yes

#481 feat(@schematics/angular): Update aliases to all use single character
  packages/schematics/angular/app-shell/schema.json
  packages/schematics/angular/application/index_spec.ts
  packages/schematics/angular/application/schema.json
  packages/schematics/angular/component/schema.json
  packages/schematics/angular/universal/schema.json
Labels: cla: yes

#477 fix(@angular-devkit/core): memory host should always refer to path from root
  packages/angular_devkit/core/src/virtual-fs/host/memory.ts
  packages/angular_devkit/core/src/virtual-fs/host/memory_spec.ts
Labels: cla: yes

#486 ci: increase timeouts for flaky tests
  .circleci/config.yml
  packages/angular_devkit/build_webpack/test/browser/rebuild_spec_large.ts
  packages/angular_devkit/build_webpack/test/karma/code-coverage_spec_large.ts
Labels: cla: yes

#484 feat(@angular-devkit/build-webpack): update internal plugins for webpack 4
  packages/angular_devkit/build_webpack/src/angular-cli-files/plugins/bundle-budget.ts
  packages/angular_devkit/build_webpack/src/angular-cli-files/plugins/karma-webpack-failure-cb.ts
  packages/angular_devkit/build_webpack/src/angular-cli-files/plugins/suppress-entry-chunks-webpack-plugin.ts
Labels: cla: yes

#482 refactor(@angular-devkit/build-webpack): use mini-css-extract-plugin
  package-lock.json
  package.json
  packages/angular_devkit/build_webpack/package.json
  packages/angular_devkit/build_webpack/src/angular-cli-files/models/webpack-configs/styles.ts
  packages/angular_devkit/build_webpack/src/angular-cli-files/plugins/cleancss-webpack-plugin.ts
  packages/angular_devkit/build_webpack/src/angular-cli-files/plugins/raw-css-loader.ts
  packages/angular_devkit/build_webpack/src/angular-cli-files/plugins/webpack.ts
Labels: cla: yes

#490 fix(@angular-devkit/schematics): Allow test runner to run private sch…
  packages/angular_devkit/schematics/testing/schematic-test-runner.ts
Labels: cla: yes

#497 feat(@angular-devkit/architect): expose builder schema
  packages/angular_devkit/architect/src/architect.ts
  packages/angular_devkit/architect/src/builder.ts
Labels: cla: yes

#320 feat(@schematics/schematics): add declaration files by default and np…
  packages/schematics/schematics/blank/project-files/__dot__npmignore
  packages/schematics/schematics/blank/project-files/tsconfig.json
Labels: cla: yes

#517 ci: update webdriver manually
  .appveyor.yml
  .circleci/config.yml
  package-lock.json
  package.json
  packages/angular_devkit/build_webpack/test/utils/default-workspaces.ts
  tests/@angular_devkit/build_optimizer/webpack/aio-app/package.json
  tests/@angular_devkit/build_optimizer/webpack/simple-app/package.json
Labels: cla: yes

#519 fix(@angular-devkit/build-webpack): workaround ES2015 minifier inlining defect
  packages/angular_devkit/build_webpack/src/angular-cli-files/models/webpack-configs/common.ts
Labels: cla: yes

#522 feat(@angular-devkit/core): add workspace.listProjectNames()
  packages/angular_devkit/core/src/workspace/workspace.ts
  packages/angular_devkit/core/src/workspace/workspace_spec.ts
Labels: cla: yes

#524 fix(@angular-devkit/build-optimizer): support fesm5 paths
  packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer.ts
Labels: cla: yes

#507 feat(devkit): add a devkit package schematic
  .monorepo.json
  packages/_/devkit/collection.json
  packages/_/devkit/package.json
  packages/_/devkit/package/factory.ts
  packages/_/devkit/package/project-files/__path__/README.md
  packages/_/devkit/package/project-files/__path__/package.json
  packages/_/devkit/package/project-files/__path__/src/index.ts
  packages/_/devkit/package/schema.d.ts
  packages/_/devkit/package/schema.json
  tsconfig.json
Labels: cla: yes

#530 fix(@angular-devkit/core): sometimes NullLogger.createChild can be ca…
  packages/angular_devkit/core/src/logger/logger.ts
Labels: cla: no

#531 feat(@angular-devkit/build-optimizer): support webpack side effects flag
  packages/angular_devkit/build_optimizer/src/build-optimizer/webpack-loader.ts
Labels: cla: yes

#534 fix(@angular-devkit/schematics): fix some optimizing issue
  packages/angular_devkit/schematics/src/tree/action.ts
  packages/angular_devkit/schematics/src/tree/action_spec.ts
Labels: cla: yes

#533 refactor(@angular-devkit/build-webpack): simplify source map config
  packages/angular_devkit/build_webpack/src/angular-cli-files/models/webpack-configs/browser.ts
Labels: cla: yes

#536 feat(@angular-devkit/build-webpack): support multi-tsconfig tslint
  packages/angular_devkit/build_webpack/src/tslint/index.ts
  packages/angular_devkit/build_webpack/src/tslint/schema.json
  packages/angular_devkit/build_webpack/test/tslint/works_spec_large.ts
Labels: cla: yes

#506 feat(@angular-devkit/build-webpack): support less version 3.x
  package-lock.json
  package.json
  packages/angular_devkit/build_webpack/package.json
Labels: cla: yes

#537 refactor(@angular-devkit/build-webpack): update webpack sri plugin
  package-lock.json
  package.json
  packages/angular_devkit/build_webpack/package.json
Labels: cla: yes

#518 feat(@angular-devkit/schematics): generate tree-shakeable services by default
  packages/schematics/angular/service/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.service.ts
  packages/schematics/angular/service/index.ts
  packages/schematics/angular/service/index_spec.ts
  packages/schematics/angular/utility/ast-utils.ts
Labels: cla: yes

#543 refactor(@angular-devkit/build-webpack): update circular dep plugin
  package-lock.json
  package.json
  packages/angular_devkit/build_webpack/package.json
Labels: cla: yes

#544 refactor: rename optimizationLevel to optimization
  packages/angular_devkit/build_webpack/src/angular-cli-files/models/build-options.ts
  packages/angular_devkit/build_webpack/src/angular-cli-files/models/webpack-configs/browser.ts
  packages/angular_devkit/build_webpack/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_webpack/src/browser/index.ts
  packages/angular_devkit/build_webpack/src/browser/schema.json
  packages/angular_devkit/build_webpack/src/dev-server/index.ts
  packages/angular_devkit/build_webpack/src/extract-i18n/index.ts
  packages/angular_devkit/build_webpack/test/browser/license-extraction_spec_large.ts
  packages/angular_devkit/build_webpack/test/browser/optimization-level_spec_large.ts
  packages/angular_devkit/build_webpack/test/browser/scripts-array_spec_large.ts
  packages/angular_devkit/build_webpack/test/browser/styles_spec_large.ts
  packages/angular_devkit/core/src/workspace/workspace_spec.ts
  packages/schematics/angular/application/files/__dot__angular.json
  tests/@angular_devkit/build_webpack/hello-world-app/.angular.json
  tests/@angular_devkit/core/workspace/angular-workspace.json
Labels: cla: yes

#540 fix(@angular-devkit/build-webpack): use direct dependencies on core…
  packages/angular_devkit/build_webpack/package.json
Labels: cla: yes

#545 fix(@angular-devkit/build-optimizer): prefix classes with tslib namespace imports
  packages/angular_devkit/build_optimizer/src/transforms/prefix-classes.ts
  packages/angular_devkit/build_optimizer/src/transforms/prefix-classes_spec.ts
Labels: cla: yes

#548 build: clear snapshot directory before publishing
  scripts/snapshots.ts
Labels: cla: yes

#551 fix(@schematics/angular): Fix typo in workspace generation
  packages/schematics/angular/application/index.ts
Labels: cla: yes

#554 fix(@angular-devkit/architect-cli): accept angular workspace filenames
  packages/angular_devkit/architect_cli/bin/architect.ts
Labels: cla: yes

#556 fix(@angular-devkit/build-webpack): always build after delete dir
  packages/angular_devkit/build_webpack/src/browser/index.ts
Labels: cla: yes

#560 fix(@schematics/angular): fix environment file path
  packages/schematics/angular/application/index.ts
Labels: cla: yes

#562 fix(@schematics/angular): remove empty fields in workspace
  packages/schematics/angular/application/index.ts
  packages/schematics/angular/e2e/index.ts
  packages/schematics/angular/workspace/files/angular.json
Labels: cla: yes

#564 fix(@schematics/angular): Correct name parse/validation for lib and app
  packages/schematics/angular/application/index.ts
  packages/schematics/angular/application/schema.json
  packages/schematics/angular/library/index.ts
  packages/schematics/angular/library/schema.json
Labels: cla: yes

#566 build: use rxjs@5.5.8 as minimum
  package-lock.json
  package.json
  packages/angular_devkit/architect/package.json
  packages/angular_devkit/architect/test/package.json
  packages/angular_devkit/architect_cli/package.json
  packages/angular_devkit/build_ng_packagr/package.json
  packages/angular_devkit/build_webpack/package.json
  packages/angular_devkit/core/package.json
  packages/angular_devkit/schematics/package.json
  packages/angular_devkit/schematics_cli/package.json
  packages/schematics/angular/utility/latest-versions.ts
  packages/schematics/package_update/package.json
  packages/schematics/update/package.json
  scripts/patch-dependencies.ts
  scripts/patches/rxjs-ts27.patch
  tests/@angular_devkit/build_optimizer/webpack/aio-app/package.json
  tests/@angular_devkit/build_optimizer/webpack/simple-app/package.json
  tests/@angular_devkit/build_webpack/hello-world-app/package.json
Labels: cla: yes

#567 fix(@schematics/angular): add build-ng-packagr when generating library
  packages/schematics/angular/library/index.ts
Labels: cla: yes

#568 feat(@angular-devkit/build-webpack): re-enable bundle budgets
  packages/angular_devkit/build_webpack/src/browser/index.ts
  packages/angular_devkit/build_webpack/src/browser/schema.json
  packages/angular_devkit/build_webpack/test/browser/bundle-budgets_spec_large.ts
Labels: cla: yes

#572 refactor(@angular-devkit/build-webpack): remove common-tags dependency
  package-lock.json
  package.json
  packages/angular_devkit/build_webpack/package.json
  packages/angular_devkit/build_webpack/src/angular-cli-files/lib/base-href-webpack/base-href-webpack-plugin_spec.ts
  packages/angular_devkit/build_webpack/src/angular-cli-files/models/webpack-configs/typescript.ts
  packages/angular_devkit/build_webpack/src/angular-cli-files/utilities/service-worker/index.ts
  packages/angular_devkit/build_webpack/src/angular-cli-files/utilities/stats.ts
Labels: cla: yes

#496 refactor(@angular-devkit/build-webpack): update dev-server to 3.1 stable
  package-lock.json
  package.json
  packages/angular_devkit/build_webpack/package.json
Labels: cla: yes

#575 fix(@angular-devkit/architect): also resolve builders locally
  packages/angular_devkit/architect/src/architect.ts
Labels: cla: yes

#577 fix(@angular-devkit/build-webpack): only open browser on first build
  packages/angular_devkit/build_webpack/src/dev-server/index.ts
Labels: cla: yes

#578 fix(@schematics/angular): add builders when running schematics
  packages/schematics/angular/application/index.ts
  packages/schematics/angular/application/index_spec.ts
  packages/schematics/angular/application/schema.d.ts
  packages/schematics/angular/application/schema.json
  packages/schematics/angular/class/index_spec.ts
  packages/schematics/angular/component/index_spec.ts
  packages/schematics/angular/directive/index_spec.ts
  packages/schematics/angular/enum/index_spec.ts
  packages/schematics/angular/guard/index_spec.ts
  packages/schematics/angular/interface/index_spec.ts
  packages/schematics/angular/library/index.ts
  packages/schematics/angular/library/index_spec.ts
  packages/schematics/angular/library/schema.json
  packages/schematics/angular/module/index_spec.ts
  packages/schematics/angular/ng-new/index.ts
  packages/schematics/angular/pipe/index_spec.ts
  packages/schematics/angular/service/index_spec.ts
  packages/schematics/angular/utility/latest-versions.ts
Labels: cla: yes

#580 ci: add snapshots for missing repos
  .monorepo.json
Labels: cla: yes

#581 test: fix missing property on application opts
  packages/schematics/angular/app-shell/index_spec.ts
  packages/schematics/angular/service-worker/index_spec.ts
  packages/schematics/angular/universal/index_spec.ts
Labels: cla: yes

#510 feat(@schematics/angular): Add schematic for ng update migrations
  packages/schematics/angular/migrations/migration-collection.json
  packages/schematics/angular/migrations/update-6/index.ts
  packages/schematics/angular/migrations/update-6/index_spec.ts
Labels: Work in Progress, cla: yes

#582 ci: remove broken snapshot url
  .monorepo.json
Labels: cla: yes

#583 fix(@schematics/angular): Remove workspace messages
  packages/schematics/angular/application/index.ts
  packages/schematics/angular/e2e/index.ts
  packages/schematics/angular/library/index.ts
Labels: cla: yes

#587 fix(@schematics/angular): Add file generation for service worker sche…
  packages/schematics/angular/service-worker/index.ts
  packages/schematics/angular/service-worker/index_spec.ts
Labels: cla: yes

#590 fix(@angular-devkit/build-angular): resolve with baseUrl instead of root
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/read-tsconfig.ts
Labels: cla: yes
