Repository angular/devkit, pull requests merged in 2018-05, with the labels that each got.

#818 fix(@schematics/angular): update animations polyfill instructions
  packages/schematics/angular/application/files/src/polyfills.ts
Labels: cla: yes

#812 fix(@angular/pwa): move manifest and commands where they belong
  packages/angular/pwa/pwa/files/root/manifest.json
  packages/angular/pwa/pwa/index.ts
  packages/angular/pwa/pwa/index_spec.ts
  packages/schematics/angular/service-worker/index.ts
  packages/schematics/angular/service-worker/index_spec.ts
Labels: cla: yes

#804 feat(@schematics/angular): use the client root as a better default for univers…
  packages/schematics/angular/universal/index.ts
  packages/schematics/angular/universal/index_spec.ts
  packages/schematics/angular/universal/schema.json
Labels: cla: yes

#822 feat(@angular-devkit/build-angular): allow poll override in dev-server
  packages/angular_devkit/build_angular/src/dev-server/index.ts
  packages/angular_devkit/build_angular/src/dev-server/schema.json
Labels: cla: yes

#823 fix(@schematics/angular): do not assume initial license
  packages/schematics/angular/workspace/files/package.json
Labels: cla: yes

#825 fix(@schematics/angular): fix code coverage path
  packages/schematics/angular/application/files/lint/__tsLintRoot__/tslint.json
  packages/schematics/angular/application/files/root/karma.conf.js
  packages/schematics/angular/application/files/root/tsconfig.app.json
  packages/schematics/angular/application/files/root/tsconfig.spec.json
  packages/schematics/angular/application/index.ts
  packages/schematics/angular/library/files/__projectRoot__/karma.conf.js
  packages/schematics/angular/library/files/__projectRoot__/tsconfig.lib.json
  packages/schematics/angular/library/files/__projectRoot__/tsconfig.spec.json
  packages/schematics/angular/library/files/__projectRoot__/tslint.json
  packages/schematics/angular/library/index.ts
Labels: cla: yes

#824 fix(@angular-devkit/build-angular): error out using karma plugin outs…
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/karma.ts
Labels: cla: yes

#828 fix(@schematics/angular): set defaultProject on update
  packages/schematics/angular/migrations/update-6/index.ts
  packages/schematics/angular/migrations/update-6/index_spec.ts
Labels: cla: yes

#827 fix(@schematics/angular): Remove module option from guard schematic
  packages/schematics/angular/guard/index.ts
  packages/schematics/angular/guard/index_spec.ts
  packages/schematics/angular/guard/schema.d.ts
  packages/schematics/angular/guard/schema.json
Labels: cla: yes

#832 fix(@schematics/angular): migrate 1.0 karma configs
  packages/schematics/angular/migrations/update-6/index.ts
  packages/schematics/angular/migrations/update-6/index_spec.ts
Labels: cla: yes

#837 fix(@angular-devkit/build-optimizer): match comments in enums
  packages/angular_devkit/build_optimizer/src/transforms/wrap-enums.ts
  packages/angular_devkit/build_optimizer/src/transforms/wrap-enums_spec.ts
Labels: cla: yes

#840 fix(@angular-devkit/build-angular): update minimum dev server version
  package-lock.json
  package.json
  packages/angular_devkit/build_angular/package.json
Labels: cla: yes

#848 feat(@angular-devkit/build-angular): allow optional karma watch
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/karma.ts
  packages/angular_devkit/build_angular/src/karma/index.ts
  packages/angular_devkit/build_angular/src/karma/schema.json
Labels: Work in Progress, cla: yes

#844 fix(@angular-devkit/build-optimizer): further improvements to enum validation
  package-lock.json
  packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer.ts
  packages/angular_devkit/build_optimizer/src/index.ts
  packages/angular_devkit/build_optimizer/src/transforms/wrap-enums.ts
  packages/angular_devkit/build_optimizer/src/transforms/wrap-enums_spec.ts
Labels: cla: yes

#731 refactor(@angular-devkit/schematics): adjust node-workflow rxjs usage
  packages/angular_devkit/schematics/tools/workflow/node-workflow.ts
Labels: cla: yes

#852 feat(@schematics/update): support scoped package registries
  packages/schematics/update/update/npm.ts
Labels: cla: yes

#795 fix(@schematics/angular): providedIn in guard
  packages/schematics/angular/guard/files/__name@dasherize__.guard.ts
Labels: cla: yes

#843 fix(@schematics/angular): Add budget configuration to update logic
  packages/schematics/angular/migrations/update-6/index.ts
  packages/schematics/angular/migrations/update-6/index_spec.ts
  packages/schematics/angular/utility/config.ts
Labels: cla: yes

#874 fix(@angular-devkit/schematics): ensure non-empty with last op
  packages/angular_devkit/schematics/tools/workflow/node-workflow.ts
Labels: cla: yes

#851 fix(@angular-devkit/build-angular): remove mangle and compress from server build
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/src/server/index.ts
Labels: cla: yes

#876 fix(@angular-devkit/build-angular): remove unused serve in protractor…
  packages/angular_devkit/build_angular/src/protractor/schema.json
Labels: cla: yes

#862 fix(@angular-devkit/schematics): add support for BOM to UpdateRecorder
  packages/angular_devkit/schematics/src/tree/recorder.ts
  packages/angular_devkit/schematics/src/tree/recorder_spec.ts
  packages/angular_devkit/schematics/src/tree/virtual.ts
Labels: cla: yes

#877 fix(@angular-devkit/schematics): fully ensure non-empty with last op
  packages/angular_devkit/schematics/tools/workflow/node-workflow.ts
Labels: cla: yes

#878 fix(@angular-devkit/build-optimizer): support 2.7+ exported enums
  packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer_spec.ts
  packages/angular_devkit/build_optimizer/src/transforms/wrap-enums.ts
  packages/angular_devkit/build_optimizer/src/transforms/wrap-enums_spec.ts
Labels: cla: yes

#884 fix(@schematics/update): respect caret and tilde ranges
  packages/schematics/update/update/index.ts
  packages/schematics/update/update/index_spec.ts
Labels: cla: yes

#871 test(@angular-devkit/core): add missing parameter in angular-workspace.json
  tests/@angular_devkit/core/workspace/angular-workspace.json
Labels: cla: yes

#886 docs: use angular.json instead of old .angular-cli.json
  CONTRIBUTING.md
Labels: cla: yes

#888 Prefix fixes
  packages/schematics/angular/component/index.ts
  packages/schematics/angular/component/index_spec.ts
  packages/schematics/angular/component/schema.json
  packages/schematics/angular/directive/index.ts
  packages/schematics/angular/directive/index_spec.ts
  packages/schematics/angular/directive/schema.json
Labels: cla: yes

#891 refactor(@angular-devkit/build-angular): update webpack related deps
  package-lock.json
  package.json
  packages/angular_devkit/build_angular/package.json
Labels: cla: yes

#904 ci: update ngcontainer version and adjust resource usage
  .circleci/config.yml
Labels: cla: yes

#900 refactor(@angular-devkit/build-angular): make node-sass optional
  packages/angular_devkit/build_angular/package.json
Labels: cla: yes

#901 fix(@schematics/update): support upper unbounded ranges
  packages/schematics/update/update/index.ts
Labels: cla: yes

#910 fix(@angular-devkit/build-angular): Remove space in "${options.host}: ${options.port}"
  packages/angular_devkit/build_angular/src/dev-server/index.ts
Labels: cla: yes

#883 docs: add snapshot links
  README.md
  scripts/templates/readme.ejs
Labels: cla: yes

#720 fix(@schematic/angular): e2e should use the prefix
  packages/schematics/angular/application/index.ts
  packages/schematics/angular/e2e/files/src/app.e2e-spec.ts
  packages/schematics/angular/e2e/schema.d.ts
  packages/schematics/angular/e2e/schema.json
Labels: cla: yes

#834 fix(@schematics/angular): generate server tsconfig to correct locatio…
  packages/schematics/angular/universal/files/root/__tsconfigFileName__.json
  packages/schematics/angular/universal/index.ts
  packages/schematics/angular/universal/index_spec.ts
Labels: cla: yes

#838 fix(@schematics/update): Allow usage strict SSL configuration
  packages/schematics/update/update/npm.ts
Labels: cla: yes

#914 fix(@schematics/angular): Fix new project default options
  packages/schematics/angular/ng-new/schema.json
Labels: cla: yes

#912 support mjs extension
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
Labels: cla: yes

#887 feat(@ngtools/webpack): resolve all file requests with the virtual fs
  packages/ngtools/webpack/src/compiler_host.ts
  packages/ngtools/webpack/src/virtual_file_system_decorator.ts
  packages/ngtools/webpack/src/webpack.ts
Labels: cla: yes

#915 fix(@schematics/schematics): should not have test node_modules specs
  packages/schematics/schematics/blank/project-files/package.json
Labels: cla: yes

#922 fix(@angular-devkit/build-angular): support server sourcemaps
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/server.ts
  packages/angular_devkit/build_angular/test/server/base_spec_large.ts
Labels: cla: yes

#919 fix(@angular-devkit/build-angular): perform surgical updates to index.html
  packages/angular_devkit/build_angular/src/angular-cli-files/plugins/index-html-webpack-plugin.ts
  packages/angular_devkit/build_angular/test/browser/index_spec_large.ts
  packages/angular_devkit/build_angular/test/browser/service-worker_spec_large.ts
Labels: cla: yes

#893 ci: add changelog generator
  package-lock.json
  package.json
  scripts/changelog.ts
  scripts/templates/changelog-feat.ejs
  scripts/templates/changelog-fix.ejs
  scripts/templates/changelog-special-thanks.ejs
  scripts/templates/changelog.ejs
Labels: cla: yes

#906 feat(@schematics/angular): use application name as title in AppComponent
  packages/schematics/angular/application/other-files/app.component.spec.ts
  packages/schematics/angular/application/other-files/app.component.ts
Labels: cla: yes

#929 fix(@schematics/angular): Fix broken unit test on new app
  packages/schematics/angular/application/other-files/app.component.spec.ts
Labels: cla: yes

#927 fix(@angular-devkit/build-optimizer): correct 2.8 enum export assignment
  packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer_spec.ts
  packages/angular_devkit/build_optimizer/src/transforms/wrap-enums.ts
  packages/angular_devkit/build_optimizer/src/transforms/wrap-enums_spec.ts
Labels: cla: yes

#930 fix(@schematics/angular): e2e should use the name
  packages/schematics/angular/application/index.ts
  packages/schematics/angular/e2e/files/src/app.e2e-spec.ts
  packages/schematics/angular/e2e/schema.d.ts
  packages/schematics/angular/e2e/schema.json
Labels: cla: yes

#925 fix(@angular-devkit/build-angular): make serve build options override
  packages/angular_devkit/build_angular/src/dev-server/index.ts
Labels: cla: yes

#933 Library schematic fixes
  packages/schematics/angular/library/index.ts
  packages/schematics/angular/library/index_spec.ts
Labels: cla: yes

#850 fix(@schematics/update): show warning for allowOutsideOutDir assets
  packages/schematics/angular/migrations/update-6/index.ts
  packages/schematics/angular/migrations/update-6/index_spec.ts
Labels: cla: yes

#944 build: update angular package to final version
  package-lock.json
  package.json
Labels: cla: yes

#932 fix(@angular-devkit/build-angular): upgrade coverage reporter
  package-lock.json
  package.json
  packages/schematics/angular/workspace/files/package.json
  tests/@angular_devkit/build_angular/hello-world-app/package.json
Labels: cla: yes

#853 feat(@angular/pwa): add content for when javascript is not available
  packages/angular/pwa/pwa/index.ts
  packages/angular/pwa/pwa/index_spec.ts
Labels: cla: yes

#907 feat(@schematics/angular): use app as an alias for the application schematic
  packages/schematics/angular/collection.json
Labels: cla: yes

#951 build: adjust mailmap
  .mailmap
Labels: cla: yes

#950 fix(@angular-devkit/build-angular): temporarily downgrade webpack to 4.6
  package-lock.json
  package.json
  packages/angular_devkit/build_angular/package.json
Labels: cla: yes

#962 refactor(@angular-devkit/core): refactor the DevServerBuilder to be e…
  packages/angular_devkit/build_angular/src/dev-server/index.ts
Labels: cla: yes

#953 fix(@schematics/update): cache npm configuration options
  packages/schematics/update/update/npm.ts
Labels: cla: yes

#972 ci: fix all circular dependencies
  packages/angular_devkit/core/src/json/schema/interface.ts
  packages/angular_devkit/core/src/json/schema/transforms.ts
  packages/angular_devkit/core/src/json/schema/visitor.ts
  packages/angular_devkit/core/src/virtual-fs/host/test.ts
  packages/angular_devkit/schematics/tools/file-system-engine-host.ts
  packages/angular_devkit/schematics/tools/node-module-engine-host.ts
  packages/angular_devkit/schematics/tools/workflow/node-workflow.ts
Labels: cla: yes

#978 fix(@schematics/package-update): use https for npm call
  packages/schematics/package_update/utility/npm.ts
Labels: cla: yes

#973 feat(@ngtools/webpack): allow custom platform transformers
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
Labels: cla: yes

#982 fix(@schematics/update): support npm auth options
  packages/schematics/update/update/npm.ts
Labels: cla: yes

#943 feat(@ngtools/webpack): add .tsx support
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/typescript.ts
  packages/ngtools/webpack/src/angular_compiler_plugin.ts
Labels: cla: yes, comp: ngtools/webpack

#983 fix(@angular-devkit/build-angular): favor project node modules with project deps
  packages/angular_devkit/build_angular/src/angular-cli-files/utilities/require-project-module.ts
Labels: cla: yes

#987 fix(@schematics/update): stabilize package list before continuing
  packages/schematics/update/update/index.ts
  packages/schematics/update/update/index_spec.ts
Labels: cla: yes

#767 feat(@angular-devkit/build-angular): add sourcemaps for external libr…
  package-lock.json
  package.json
  packages/angular_devkit/build_angular/package.json
  packages/angular_devkit/build_angular/src/angular-cli-files/models/build-options.ts
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
  packages/angular_devkit/build_angular/src/browser/schema.d.ts
  packages/angular_devkit/build_angular/src/browser/schema.json
  packages/angular_devkit/build_angular/src/dev-server/schema.json
  packages/angular_devkit/build_angular/src/karma/schema.json
  packages/angular_devkit/build_angular/src/server/schema.d.ts
  packages/angular_devkit/build_angular/src/server/schema.json
  packages/angular_devkit/build_angular/test/browser/vendor-source-map_spec_large.ts
Labels: cla: yes

#863 feat(@angular-devkit/build-angular): add watch mode to server
  packages/angular_devkit/build_angular/src/server/index.ts
  packages/angular_devkit/build_angular/src/server/schema.d.ts
  packages/angular_devkit/build_angular/src/server/schema.json
  packages/angular_devkit/build_angular/test/server/base_spec_large.ts
Labels: cla: yes

#979 fix(@schematics/angular): remove angularCli in Karma when updating
  packages/schematics/angular/migrations/update-6/index.ts
  packages/schematics/angular/migrations/update-6/index_spec.ts
Labels: cla: yes

#993 fix(@angular-devkit/build-angular): never split polyfills in test
  packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/test.ts
Labels: cla: yes

#985 fix(@schematics/angular): use old config root to set root and sourceR…
  packages/schematics/angular/migrations/update-6/index.ts
  packages/schematics/angular/migrations/update-6/index_spec.ts
Labels: cla: yes
